server:
  port: 8989
spring:
  kafka:
    bootstrap-servers: localhost:29092
topic:
  dishes-input: postgres.public.dishes
  restaurants-input: postgres.public.restaurants
  enriched-restaurants-output: enriched.restaurants