server:
  port: 8788
spring:
  application:
    name: kotlin-kafka-streams
  kafka:
    bootstrap-servers: localhost:29092

topic:
  dishes-input: postgres.public.dishes
  restaurants-input: postgres.public.restaurants
  enriched-restaurants-output: enriched.restaurants